### ISSUE TITLE
Steam proton works only once

### ISSUE THREAD

**Issue by solipsist01** [games-on-whales/gow#145]
Hello.

Great repo. Really brilliant :) My mind was really blown when i got it working.

However, i have a strange issue.
i've got a nuc12 with iris xe IGPU / intel. with a hdmi dummy plug.
I run Debian Bookworm  / cli only. No desktop environment.

i have cloned the latest master, and launch like so:
./run-gow --platform headless --gpu intel --app steam up

this is my user.env

```
XORG_IPC=shareable
# XORG_VERBOSE=6

SHARED_IPC=service:xorg
LOCAL_STATE=/gow/local_state
TIME_ZONE=Europe/Amsterdam
###################
# This section is for running in "headless" mode, without a desktop already
# running on your host
###################
XORG_SOCKET=xorg
XORG_DISPLAY=:99

# Change these to suit your preferences
XORG_RESOLUTION=1920x1080
XORG_REFRESH_RATE=60
XORG_DISPLAY_PORT=HDMI-1
XORG_FORCE_RESOLUTION=true

PULSE_SERVER=unix:/tmp/pulse/pulse-socket
PULSE_SOCKET_HOST=pulse

####################
# Services that use udev in order to get devices
# needs to be on the same network
# This is because they need the udev PF_NETLINK socket
UDEVD_NETWORK=service:udevd

```

I can connect with moonlight. i have logged into steam, and enabled Proton.
I have installed a game called "My friend peppa pig" (this game is "for my 6 year old son" ;))
i "really don't play this game myself!!, seriously!" 
nono "for real!,... asking for a friend" ;)

All works wonderful. Performance rocks as well. However, when i quit this game, and relaunch the game, it starts, and stops immediately.

After i stop the containers, and rerun the stack, i can play the game again. once.
I have tried every proton version so far. removed the .steam folder and restarted.
Non proton games like retroarch etc run fine.

There's logging in the console like so:
```
gow-steam-1     | Game process updated : AppID 1635590 "/home/retro/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=1635590 -- /home/retro/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/retro/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/retro/.steam/debian-installation/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/retro/.steam/debian-installation/steamapps/common/My Friend Peppa Pig/My Friend Peppa Pig.exe'", ProcID 1551, IP 0.0.0.0:0
gow-steam-1     | Game process removed: AppID 1635590 "/home/retro/.steam/debian-installation/ubuntu12_32/reaper SteamLaunch AppId=1635590 -- /home/retro/.steam/debian-installation/ubuntu12_32/steam-launch-wrapper -- '/home/retro/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper'/_v2-entry-point --verb=waitforexitandrun -- '/home/retro/.steam/debian-installation/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/retro/.steam/debian-installation/steamapps/common/My Friend Peppa Pig/My Friend Peppa Pig.exe'", ProcID 1551
gow-steam-1     | ThreadGetProcessExitCode: no such process 1591
gow-steam-1     | ThreadGetProcessExitCode: no such process 1560
gow-steam-1     | ThreadGetProcessExitCode: no such process 1557
gow-steam-1     | ThreadGetProcessExitCode: no such process 1555
gow-steam-1     | ThreadGetProcessExitCode: no such process 1551
gow-steam-1     | ThreadGetProcessExitCode: no such process 1549
gow-steam-1     | ThreadGetProcessExitCode: no such process 1433
gow-steam-1     | ThreadGetProcessExitCode: no such process 1432
```

Does anyone have, "any" idea?

**Comment by ABeltramo** [comment]
Thanks for testing it out!  

We are still experimenting a lot with everything, and I'm afraid I can't reproduce your specific issue since I don't own the game, but there are a few places where you can look for clues; see [the docs](https://games-on-whales.github.io/gow/steam.html#_something_is_wrong_where_are_the_logs).

Hope that helps, let us know how it goes!
