### ISSUE TITLE
Emulationstation DE container crashes on start

### ISSUE THREAD

**Issue by harshi3t** [games-on-whales/gow#153]
Really awesome project. This is the closest I've come to be able to play retro games from my unraid server.

I spin up the containers using this command,
`./run-gow --platform headless --gpu intel --app emulationstationde up`

Also, had to edit context field within `emulationstationde.yml` file to `./images/es-de`. At the moment it points to incorrect path.

Emulationstation DE container crashes at start with the following log,
```
[2023-09-05 13:36:50] 
[2023-09-05 13:36:50] [ /etc/cont-init.d/10-setup_user.sh: executing... ]
[2023-09-05 13:36:50] **** Configure default user ****
[2023-09-05 13:36:50] Setting default user uid=1000(retro) gid=1000(retro)
[2023-09-05 13:36:51] Setting umask to 000
[2023-09-05 13:36:51] Ensure retro home directory is writable
[2023-09-05 13:36:51] Ensure XDG_RUNTIME_DIR is writable
chown: cannot access '': No such file or directory
``` 
I'm unable to get the path that is resolving to `''` in the last line.
As specified in doc, non root users have full rw permissions to `local_state` and other bios/rom/media folders.

Firefox and Retroarch containers load without errors and moonlight streams them without issues.

OS: Unraid 6.12.3
GPU: Intel UHD Graphics 730

**Comment by tostc** [comment]
I've run in the same issue as you. In the dockerfile inside the images directory of emulationstation, the `ENV XDG_RUNTIME_DIR=/tmp/.X11-unix` needs to be set. After that you can rebuild the container and everything works fine.

**Comment by ABeltramo** [comment]
First off, sorry for the very late reply.  
If it's just an env variable missing, you can easily add it to the env files without having to rebuild the images.

As a side note, GOW and `run-gow` are becoming more and more "legacy" at the moment, I suggest you to check out [Wolf](https://games-on-whales.github.io/wolf/stable/user/quickstart.html) instead.
