### ISSUE TITLE
Steam Container Resolution

### ISSUE THREAD

**Issue by salty2011** [games-on-whales/gow#154]
The steam container by default only supports 1280x720 even though moonligh client is set to 1080p or 4k. The stream will be at that resolution but the container is at the aforementioned resolution.

**Work Around**

1. For each game, goto the properties of the game in steam ui and set the specific resolution wanted
2. Launch the game and now you have the option to set the resolution to specified resolution

**Expected Behavior**
To be clear not sure if this is by design or a bug so just listing my opinion as a user

- Steam container should default to the resolution set by the moonlight client
- Steam Big Picture Mode should use that resolution as the default for games when launching
- Can see some utility in have some override option

**Comment by ABeltramo** [comment]
I'm closing down old issues, this has been completely fixed by [Wolf](https://github.com/games-on-whales/wolf) which is able to automatically spin up virtual desktops matching the client resolution.
