### ISSUE TITLE
problem on startup sunshine docker

### ISSUE THREAD

**Issue by flimby1** [games-on-whales/gow#160]
Hi all,
I was trying to configure game on wolf on my server that have a J5005 CPU with his integrated GPU (an Intel UHD Graphics 605)
All seems configured correctly but when I try to launch an application the sunshine docker returned me this error:
gow-sunshine-1  | [2023:10:22:12:08:14]: Error: Couldn't load cuda: -1
gow-sunshine-1  | [2023:10:22:12:08:14]: Error: Environment variable WAYLAND_DISPLAY has not been defined
gow-sunshine-1  | [2023:10:22:12:08:14]: Info: Detecting connected monitors
I also try to force the intel driver by using the -g intel option but the problem remain.
Someone can help me?

**Comment by ABeltramo** [comment]
I'm sorry for missing this issue, a long while has passed since you've posted this and Wolf is getting more and more capable; would you like to [try it out](https://games-on-whales.github.io/wolf/stable/user/quickstart.html)?
