### ISSUE TITLE
Run GOW concurrently with desktop environment

### ISSUE THREAD

**Issue by cubimon** [games-on-whales/gow#167]
Hello,

Thanks for this awesome piece of software, I am wondering if it is possible to have a desktop environment running and using another desktop environment in a game on the same gpu/a virtual monitor. I tried so, but it switches to TTY1 and when I switch back to by local desktop environment outside the container the screen gets black, is there a way to have both desktops running concurrently?

**Comment by ABeltramo** [comment]
That's one of the main reasons why we're working on [Wolf](https://games-on-whales.github.io/wolf/stable/index.html), have you tried that out?

**Comment by cubimon** [comment]
Thanks, this sounds good, I guess I have to try it out and play around with it :)

**Comment by ABeltramo** [comment]
Have fun!
