### ISSUE TITLE
Showing error 'X11 connection rejected because of wrong authentication' when running from ssh shell

### ISSUE THREAD

**Issue by c3m3gyanesh** [games-on-whales/gow#172]
I am trying to run in headless mode. I updated the compose file as per monitor requirements instructions.
I run as below:
./run-gow --platform headless --gpu nvidia --app steam up

I get error:
X11 connection rejected because of wrong authentication

The gow-xorg shows error :
gow-xorg-1      | error: could not open display

How can i fix the 'X11 connection rejected because of wrong authentication' error? I am running gow as a non-root user.

**Comment by ABeltramo** [comment]
The GOW script is getting rusty and unmaintained; I'm working on Wolf https://github.com/games-on-whales/wolf as a replacement for this stack, would you be interested in trying it out?
