### ISSUE TITLE
Can't stream using the `run-gow` script

### ISSUE THREAD

**Issue by guozanhua** [games-on-whales/gow#175]
At Ubuntu 24.04 LTS (GNU/Linux 6.8.0-35-generic x86_64)

=====================
retroarch-1  | sh: 1: xdg-screensaver: not found
^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 2/2
 ✔ Container gow-retroarch-1  Stopped                                                                                                                                                               0.5s
 ✔ Container gow-sunshine-1   Stopped                                                                                                                                                               1.2s
canceled
cloudgame@cloudgame-server1:~/gow$ which xdg-screensaver
/usr/bin/xdg-screensaver

**Comment by ABeltramo** [comment]
The GOW script is getting rusty and unmaintained; I'm working on Wolf https://github.com/games-on-whales/wolf as a replacement for this stack, would you be interested in trying it out?

**Comment by guozanhua** [comment]
cloudgame@cloudgame-server1:~/gow$ sudo ./run-gow --streamer wolf --app retroarch up -d
Running docker compose...
WARN[0000] /dev/fd/63: `version` is obsolete
WARN[0000] /dev/fd/62: `version` is obsolete
[+] Running 25/25
 ✔ wolf Pulled                                                                                                                                                                                    259.8s
   ✔ 1e223e85e28d Pull complete                                                                                                                                                                    51.4s
   ✔ 3c8727552f55 Pull complete                                                                                                                                                                    51.7s
   ✔ 0c412ee7eeab Pull complete                                                                                                                                                                    51.7s
   ✔ 2b2ef655aaa2 Pull complete                                                                                                                                                                    51.8s
   ✔ d0a6c4fb837e Pull complete                                                                                                                                                                   188.0s
   ✔ 4fa79d9500bb Pull complete                                                                                                                                                                   189.9s
   ✔ d988ae42b629 Pull complete                                                                                                                                                                   190.0s
   ✔ e8b1488165dd Pull complete                                                                                                                                                                   190.0s
   ✔ 888caa23875f Pull complete                                                                                                                                                                   190.1s
   ✔ aba43f285381 Pull complete                                                                                                                                                                   190.2s
   ✔ ef00098d542d Pull complete                                                                                                                                                                   190.8s
   ✔ 6efcda02934c Pull complete                                                                                                                                                                   191.0s
   ✔ 28c454fdfd9e Pull complete                                                                                                                                                                   191.1s
   ✔ a6f62ccb2f0f Pull complete                                                                                                                                                                   191.2s
   ✔ 2534c266e570 Pull complete                                                                                                                                                                   254.0s
   ✔ 3be3917f15a3 Pull complete                                                                                                                                                                   254.1s
   ✔ 8db1ff2781cd Pull complete                                                                                                                                                                   254.2s
   ✔ 07e77c500089 Pull complete                                                                                                                                                                   254.3s
   ✔ f5c6fc524612 Pull complete                                                                                                                                                                   255.5s
   ✔ 7c35f050ee0e Pull complete                                                                                                                                                                   255.6s
   ✔ bcd8bd0a78ea Pull complete                                                                                                                                                                   255.6s
   ✔ cfadf5416b44 Pull complete                                                                                                                                                                   256.2s
   ✔ 0beff83c88cf Pull complete                                                                                                                                                                   256.3s
   ✔ 523d07a66c63 Pull complete                                                                                                                                                                   256.3s
WARN[0259] Found orphan containers ([gow-sunshine-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
[+] Running 2/2
 ✔ Container gow-retroarch-1  Started                                                                                                                                                               2.5s
 ✔ Container gow-wolf-1       Started                    
============================================================
when switch to wolf, how to input pair code in host? the sunshine web ui  is not worked in wolf stream

**Comment by ABeltramo** [comment]
Please don't use the `run-gow` script; follow the instructions on the [quickstart docs](https://games-on-whales.github.io/wolf/stable/user/quickstart.html)

**Comment by guozanhua** [comment]
Now it works!By the way, could wolf share a server to multi-users, currently if one user paired the server, others can't paired the server until the paired user quit moonlight client
