### ISSUE TITLE
Unsupported config option 'runtime'

### ISSUE THREAD

**Issue by ABeltramo** [games-on-whales/gow#35]
I'm trying to run gow on Proxmox inside a Ubuntu 20.04 VM with Intel GVT-g enabled but for some reason I get a error:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.retroarch: 'runtime'
Unsupported config option for services.sunshine: 'runtime
``` 

I would glady help to test support for a Intel iGPU.

```
sudo lshw -c video
  *-display                 
       Beschreibung: VGA compatible controller
       Produkt: Iris Plus Graphics 655
       Hersteller: Intel Corporation
       Physische ID: 0
       Bus-Informationen: pci@0000:01:00.0
       Logischer Name: /dev/fb0
       Version: 01
       Breite: 64 bits
       Takt: 33MHz
       Fähigkeiten: pciexpress msi pm vga_controller bus_master cap_list fb
       Konfiguration: depth=32 driver=i915 latency=0 mode=1024x768 visual=truecolor xres=1024 yres=768
       Ressourcen: iomemory:80-7f irq:41 memory:c0000000-c0ffffff memory:800000000-80fffffff
```

_Originally posted by @tristan-k in https://github.com/games-on-whales/gow/issues/21#issuecomment-890565173_

**Comment by ABeltramo** [comment]
Hello @tristan-k
First of, thanks for taking the time to checkout GOW!

I believe you are running a very old docker-compose version, can you try to update it if possible? The error message you are getting means that your current version is not supporting the `runtime` option which was added many moons ago (docker compose format 2.3 released 2017-09-05).

Alternatively you can comment out the lines in the `docker-compose.yml`
```yaml
runtime: ${DOCKER_RUNTIME}
```
like [here](https://github.com/games-on-whales/gow/blob/a2be8dc20d3005b2425bfdc7320b91ff5a9e4f24/docker-compose.yml#L86).
You are likely to bump into other unsupported features though.

**Comment by tristan-k** [comment]
Thanks. I'm sorry I must have missed that. Now I can pull.
