### ISSUE TITLE
Can't connect to web interface

### ISSUE THREAD

**Issue by phirestalker** [games-on-whales/gow#58]
When I try to connect to the machine running gow through https://[ip address]:47990 I get the following error in Chrome.

You cannot visit 192.168.133.138 right now because the website sent scrambled credentials that Chrome cannot process. Network errors and attacks are usually temporary, so this page will probably work later.

What am I doing wrong?

**Comment by ABeltramo** [comment]
I'm sorry for the late reply, that's a know issue on Sunshine. The web interface is hosted via HTTPS and the certificate is a self signed one which is not recognized as secure by the latest Firefox/Chrome versions.

My suggestion is to skip the web interface altogether and just pair clients by using `curl <SUNSHINE_IP>:47989/pin/<MOONLIGHT_PIN>` as stated in the [docs](https://games-on-whales.github.io/gow/installation/debian-headless/)
