### ISSUE TITLE
Adding custom keyboard layout support

### ISSUE THREAD

**Issue by bigredutingal** [games-on-whales/gow#60]
I think it might be useful to add keyboard layout support, perhaps via environment variable in dockerfile or via config file.

**Comment by bigredutingal** [comment]
Found a workaround for those having the same problem and can't type their password correctly.

From your kubernetes master node or docker admin server : 

``` kubectl exec -it -n <namespace> <pod_name> -c xorg -- bash ```

You will be inside xorg container, you can then do ``` setxkbmap ```, in my case ``` setxkbmap fr ``` do the trick.

**Comment by ABeltramo** [comment]
Although this is no longer relevant Wolf supports different keyboard layouts, see [the docs](https://games-on-whales.github.io/wolf/stable/user/configuration.html#_changing_and_switching_keyboard_layouts_in_wolf_apps_containers)
