### ISSUE TITLE
Tmpfs.size invalid when running docker-compose pull

### ISSUE THREAD

**Issue by curiousblueprints** [games-on-whales/gow#65]
Ubuntu server 20.04.3 LTS
Docker Compose version v2.2.3
Docker version 20.10.12, build e91ed57

I'm following the instructions for headless Ubuntu. I receive the following error during `docker-compose pull`:

`error while interpolating services.retroarch.volumes.[].tmpfs.size: failed to cast to expected type: strconv.ParseInt: parsing "500M": invalid syntax`

If I go into the .yml file and manually edit it to "500M", it works.

**Comment by zb140** [comment]
Apparently the magic that automatically turns `500M` into `524288000` happens _before_ variable interpolation... I also tried changing the `SHM_SIZE` in the `.env` file to just `500` and putting `size: "${SHM_SIZE}M"` in `docker-compose.yml` but that didn't work either 😦 .  I guess if we want it to be a variable we're going to just have to put an integer number of bytes in `.env`.

**Comment by ABeltramo** [comment]
I guess this changed on docker-compose v2. I guess we can safely remove that from the .env file if it's causing troubles since it's such a low level detail that probably no one will ever modify.

**Comment by zb140** [comment]
This may be fixed now, with the newest `docker-compose`.  I'm using v2.5.0 and I no longer get the error.

**Comment by zb140** [comment]
I'm going to go ahead and close this -- now that we've added the `run-gow` script and switched to docker compose v2, we're still not seeing this error anymore. If anyone runs into it again, please reopen.
