### ISSUE TITLE
Allow Setting the UID and GID

### ISSUE THREAD

**Issue by noinip** [games-on-whales/gow#70]
I'm on unraid and would like to be able to set those values to 99:100

**Comment by noinip** [comment]
So far I have managed to do this by editing the /common/setup-retro-user and setting them to what I want
UUID=99
UGID=100

**Comment by zb140** [comment]
This should be fixed with #76 .

**Comment by zb140** [comment]
Nope, I spoke too soon, there's still some work to do here.
