### ISSUE TITLE
Conflict with docker-compose (ubuntu repo) and docker compose (curl from docker)

### ISSUE THREAD

**Issue by QuaiGoner** [games-on-whales/gow#80]
Hello! I am trying to launch headless instance of retroarch with that line:
![image](https://user-images.githubusercontent.com/41058180/189299065-4b285a94-b265-4ede-9c6c-42e66140c127.png)
but i get docker-compose is old error
![image](https://user-images.githubusercontent.com/41058180/189299134-71ebc82b-3b7d-4fa3-8301-fb3cc17f9ab7.png)
I do have installed docker compose v2.10.2 but system is still using the old version (docker-compose)
can you help with that?
![image](https://user-images.githubusercontent.com/41058180/189299343-e9963978-bebc-4e51-a905-efe4ceb41ba7.png)

**Comment by Sparticuz** [comment]
`which docker-compose`, then delete it. You can also reinstall docker compose v2 and it will probably recreate a new docker-compose binary.

**Comment by Sparticuz** [comment]
closed by #81
