### ISSUE TITLE
`XORG_FORCE_RESOLUTION` doesn't work

### ISSUE THREAD

**Issue by zb140** [games-on-whales/gow#99]
Attempts to force a resolution that was not autodetected will fail right now because the `cvt` tool is missing from the Xorg container.  We should either add that tool (and verify that forcing resolution now works) or remove the "forced resolution" support if we don't think it's useful anymore.

**Comment by ABeltramo** [comment]
It was an early days hack to force Xorg to use the specified resolution.  

We should probably fix the root cause instead (but possibly leave that "last resort" solution documented somewhere?)

**Comment by zb140** [comment]
> We should probably fix the root cause instead (but possibly leave that "last resort" solution documented somewhere?)

Yes, I agree with fixing root causes most of the time, but I'm actually not sure what the root cause really is 😄 I was really just splitting this out of #98, where it was originally noticed.  In fact, I might be tempted to argue that the root cause is "attempting to use a forced resolution in the first place", for which the fix would be to just remove the feature 😁
